from driftwatch.review.models import Finding

CODE_FENCE = "```"

_SEVERITY_EMOJI = {
    "critical": "🔴",
    "high": "🟠",
    "medium": "🟡",
    "low": "🔵",
    "info": "⚪",
}

_EVIDENCE_LABELS = {
    "diff": "Diff",
    "ast": "AST",
    "semgrep": "Semgrep",
    "bandit": "Bandit",
    "gitleaks": "Gitleaks",
    "llm": "LLM",
}


def format_finding_comment(finding: Finding) -> str:
    emoji = _SEVERITY_EMOJI.get(finding.severity, "")
    body = (
        f"### {emoji} {finding.category.title()}: {finding.title}\n\n"
        f"**Issue**\n\n{finding.description}\n\n"
    )

    if finding.evidence:
        evidence_lines = "\n".join(
            f"- {_EVIDENCE_LABELS.get(e.source, e.source)}: {e.description}"
            + (f" (`{e.file_path}:{e.start_line}`)" if e.start_line else "")
            for e in finding.evidence
        )
        body += f"**Evidence**\n\n{evidence_lines}\n\n"

    if finding.suggested_fix:
        body += f"**Suggested fix**\n\n{finding.suggested_fix}\n\n"

    static_corroborated = any(e.source in {"semgrep", "bandit", "gitleaks"} for e in finding.evidence)
    body += (
        f"**Validation**\n\n"
        f"Status: `{finding.validation_status}`  \n"
        f"Static analysis: {'corroborated' if static_corroborated else 'not corroborated'}  \n"
        f"Validation score: {finding.validation_score}  \n"
        f"LLM confidence: {finding.llm_confidence}\n\n"
        f"---\n"
        f"*Posted automatically by DriftWatch AI Code Reviewer. Findings are "
        f"suggestions generated by automated analysis — please verify before "
        f"making changes.*"
    )
    return body
