from driftwatch.review.models import Finding


def format_pr_summary(files_analyzed: int, candidates: list, decided: list[Finding], posted: list[Finding]) -> str:
    accepted = sum(1 for f in decided if f.validation_status == "accepted")
    needs_review = sum(1 for f in decided if f.validation_status == "needs_review")
    rejected = sum(1 for f in decided if f.validation_status == "rejected")

    by_category: dict[str, int] = {}
    for finding in posted:
        by_category[finding.category] = by_category.get(finding.category, 0) + 1

    rows = "\n".join(f"| {category.title()} | {count} |" for category, count in sorted(by_category.items()))
    if not rows:
        rows = "| (none) | 0 |"

    return (
        f"## 🤖 DriftWatch AI Code Review\n\n"
        f"### Summary\n\n"
        f"- Files analyzed: {files_analyzed}\n"
        f"- Candidate findings: {len(candidates)}\n"
        f"- Validated findings: {accepted}\n"
        f"- Rejected findings: {rejected}\n"
        f"- Needs review (below the auto-post threshold): {needs_review}\n"
        f"- Posted as inline comments: {len(posted)}\n\n"
        f"### Findings posted\n\n"
        f"| Category | Count |\n|---|---:|\n{rows}\n\n"
        f"> Findings are suggestions generated by automated analysis, "
        f"corroborated where possible with static analysis (Semgrep/Bandit) "
        f"and validated before posting. Reviewers should still verify them "
        f"before making changes.\n"
    )
