from driftwatch.review.models import Finding


def format_pr_summary(files_analyzed: int, candidates: list, posted: list[Finding]) -> str:
    by_category: dict[str, int] = {}
    for finding in posted:
        by_category[finding.category] = by_category.get(finding.category, 0) + 1

    rows = "\n".join(f"| {category.title()} | {count} |" for category, count in sorted(by_category.items()))
    if not rows:
        rows = "| (none) | 0 |"

    return (
        f"## 🤖 DriftWatch AI Code Review\n\n"
        f"### Summary\n\n"
        f"- Files analyzed: {files_analyzed}\n"
        f"- Candidate findings: {len(candidates)}\n"
        f"- Posted findings: {len(posted)}\n\n"
        f"### Findings\n\n"
        f"| Category | Count |\n|---|---:|\n{rows}\n\n"
        f"> This review is generated by an unvalidated AI pipeline (Phase 1 — no "
        f"independent evidence checking yet). Treat findings as suggestions to "
        f"investigate, not confirmed issues.\n"
    )
